version: '3.8'

services:
  # Laravel Backend
  laravel-backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: perfil-user-backend
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
      - ./storage:/var/www/html/storage
      - ./bootstrap/cache:/var/www/html/bootstrap/cache
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_URL=http://localhost:8000
      - DB_CONNECTION=mysql
      - DB_HOST=easypanel.carlosvinicius.xyz
      - DB_PORT=1212
      - DB_DATABASE=user
      - DB_USERNAME=mysql
      - DB_PASSWORD=admin
      - CACHE_DRIVER=file
      - SESSION_DRIVER=file
      - QUEUE_CONNECTION=sync
    networks:
      - perfil-user-network

  # Redis Cache (Opcional - para cache)
  redis:
    image: redis:7-alpine
    container_name: perfil-user-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - perfil-user-network

volumes:
  redis_data:
    driver: local

networks:
  perfil-user-network:
    driver: bridge 